# Generated by Django 5.2.1 on 2025-06-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_appuser_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='example',
            name='input_example',
        ),
        migrations.RemoveField(
            model_name='example',
            name='output_example',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_sample',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output_data',
        ),
        migrations.AlterField(
            model_name='example',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examples_group', to='App.problem'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_group', to='App.problem'),
        ),
    ]
