# Generated by Django 5.2.1 on 2025-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_example_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='examples',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_cases',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
