# Generated by Django 5.2.1 on 2025-06-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_example_examples_testcase_test_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_code_python', models.TextField(blank=True, null=True)),
                ('base_code_cpp', models.TextField(blank=True, null=True)),
                ('base_code_java', models.TextField(blank=True, null=True)),
                ('base_code_js', models.TextField(blank=True, null=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='starter_code', to='App.problem')),
            ],
        ),
    ]
