# Generated by Django 5.2.1 on 2025-06-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_startercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
    ]
