# Generated by Django 5.2.1 on 2025-07-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_problem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
